### ISSUE TITLE
Drop-Down List not rendered right when used with tab template

### ISSUE THREAD

**Issue by frostless** [PeterStaev/NativeScript-Drop-Down#157] opened 2018-01-06 06:17 UTC
When I followed the instructions in ReadMe to implement the dropdown on a simple "helloworld" project, it works as expected. But when I tried to use it on my own tab-based template project, it did not really work.(I put the code in one of the tab component) Mostly because the items in the drop down list were not rendered at all.  I compared the settings between these two projects but I could not figure out where the problems are. I suppose though, it is because there is an extra middle layer tabs component in my project.

That is how it rendered:

<img width="389" alt="screen shot 2018-01-06 at 11 28 28 pm" src="https://user-images.githubusercontent.com/24716506/34639715-58dc58ca-f339-11e7-8ad0-053d99590eb4.png">

Not too sure if that is an issue, but I do want to use the convenient drop down feature on my tab-based template project.

Here is the [link](https://github.com/NativeScript/template-tab-navigation-ng) to the repo of the tab template.

[Here](https://we.tl/Y6XORcsS2k) is the HelloWorld app that renders the drop down well.

[Here](https://we.tl/qki30D26UY) is the Tab app that does not render the drop down well.
  
  @DickSmith @jogboms 
 Would you mind shedding some lights on this?

**Comment by PeterStaev** [comment] 2018-01-06 22:30
Hi @frostless , 

Thanks for the demo apps! I was able to simulate the problem with them, but since I'm not that big of an Angular expert, so far I'm not able to trace what causes this behavior. So far what I've traced is that when you use the plugin with tabs, excessive amount of `loaded` and `unloaded` events are triggered. While if you use it in a non-tab interface only one `loaded` event is triggered. So I suspect something related to this, but again not sure what 😢 

Ping @jogboms , @DickSmith as I think they are more experienced with Angular so they might have some ideas on this.

**Comment by frostless** [comment] 2018-01-06 22:33
Thanks Peter Staev,

I will try to ping them.

Cheere

**Comment by jogboms** [comment] 2018-01-07 06:02
@frostless I'd try to see if I could find anything useful.

**Comment by PeterStaev** [comment] 2018-02-14 20:37
A similar problem happens on android (#163)

**Comment by Ross-Jo** [comment] 2018-06-25 13:50
+1. 
Similar but bit different problem exists. 
Procedure to reproduce the problem
1. Add this 'NativeScript-Drop-Down' plugin to a bit old nativescript-tab-template,
2. After that, push the tab inside the template down to the page with 'androidTabsPosition="bottom"' option,
3. Lastly, if you move between the tabs super fast(+ as well as turning on and off the emulator)
, at some point, a label(mostly the first item of the dropdown items list) which should be shown by a dropdown component suddenly disappears.

<img width="379" alt="2018-06-25 10 46 31" src="https://user-images.githubusercontent.com/14027563/41853829-ae194f94-78c9-11e8-9fdb-beaf48d4b870.png">

<img width="383" alt="2018-06-25 10 46 18" src="https://user-images.githubusercontent.com/14027563/41854040-303220aa-78ca-11e8-92f4-d0cb4f3b1cee.png">

**Comment by Ross-Jo** [comment] 2018-06-25 13:54
And this is the sample code
[sample.zip](https://github.com/PeterStaev/NativeScript-Drop-Down/files/2133373/sample.zip)

**Comment by des-esseintes** [comment] 2018-07-03 12:53
same problem. created sample project from scratch containing tabview with 4 tabs (on the bottom), placed dd on the first one,  when switching tabs 2->1->0 the dropdown on tab0 shows no element selected, like the image above.

main.xml:
```
<Page loaded="loaded" xmlns:dd="nativescript-drop-down">
	<StackLayout>
		<TabView androidTabsPosition="bottom" id="tabview" selectedIndexChanged="tab_change">
			<TabViewItem title="A">
				<StackLayout>
					<dd:DropDown items="{{ d_days }}" selectedIndex="{{ d_selected }}" id="d_days" />
				</StackLayout>
			</TabViewItem>
			<TabViewItem title="B">
				<Label text="1" />
			</TabViewItem>
			<TabViewItem title="C">
				<Label text="1" />
			</TabViewItem>
			<TabViewItem title="D">
				<Label text="1" />
			</TabViewItem>
		</TabView>
	</StackLayout>
</Page>
```

and main.js:
```
var Observable = require("data/observable").Observable;
var ObservableArray = require("data/observable-array");

var page;
var model;

const days_of_the_week=["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

exports.loaded = function(args) {
	page = args.object;
	model = new Observable({});
	model.set("d_days", new ObservableArray.ObservableArray(days_of_the_week));
	model.set("d_selected", 2);
	page.bindingContext = model;
};

exports.tab_change = function(args) {
//	console.log(args.object.selectedIndex);
};
```

**Comment by des-esseintes** [comment] 2018-07-03 12:54
![screenshot_1530621972](https://user-images.githubusercontent.com/6807816/42221019-4ce8e8b8-7ed9-11e8-8661-7f0cceca972b.png)
![screenshot_1530621980](https://user-images.githubusercontent.com/6807816/42221020-4d07cabc-7ed9-11e8-9a0d-2b8aaa2d3d6c.png)

**Comment by priyankcommits** [comment] 2019-02-06 13:58
thread bump, anyone find any solutions to this problem ?

**Comment by PeterStaev** [comment] 2019-03-16 07:52
Hey guys, I've recircled onto this task after updating the iOS side to use the new recommended way of creating the native control in TNS 5.0. And found the following:

@frostless - after upgrading your project to TNS 5.2 and NG 7.2 noticed that you have a problem with your imports. You are adding the `DropDownModule` only in the `app.module.ts`, but your app uses lazy loading routes for the tab. So you actually need to import the `DropDownModule` in the module for your tabs. After making this change the widget started working fine. 

@Ross-Jo - after upgrading your project to TNS 5.2 and NG 7.2 I was not able to simulate the problem. 

@des-esseintes - I've created a brand new project with TNS 5.2 and used your code, but I was not able to simulate the problem. 

With this said, I will close this task. In case any of you still have problems with the widget with the latest version of TNS/NG/widget please provide a playground link or a sample app and I will reopen it.

**Closed by PeterStaev** 2019-03-16 07:52 UTC
Labels: angular, bug, help wanted
