### ISSUE TITLE
Cannot find module 'ui/list-picker'.

### ISSUE THREAD

**Issue by tahir-jamil** [PeterStaev/NativeScript-Drop-Down#202] opened 2019-04-18 18:44 UTC
error logs
`node_modules/nativescript-drop-down/drop-down.d.ts(19,29): error TS2307: Cannot find module 'ui/list-picker'.`

i have also imported the module in app.module.ts its working but i have this exception too 
maybe when build for productions which will effect the productions please help me in fixing this 

> hear are the imports in drop-down.d.ts
```
import { ObservableArray } from "data/observable-array";
import { CoercibleProperty, EventData, Property, View } from "ui/core/view";
import { GestureTypes } from "ui/gestures/gestures";
import { ItemsSource } from "ui/list-picker";
```
> i just change these to 
```
import { ItemsSource } from "tns-core-modules/ui/list-view/list-view";
import { EventData, View, CoercibleProperty, Property } from "tns-core-modules/ui/page/page";
import { ObservableArray } from "tns-core-modules/data/observable-array/observable-array";
```
> know their is no errors

**Comment by PeterStaev** [comment] 2019-04-18 20:02
Duplicate of #198

**Closed by PeterStaev** 2019-04-18 20:02 UTC

**Comment by tahir-jamil** [comment] 2019-04-18 20:07
thanks for your quick response
