### ISSUE TITLE
Does not Jump to selectedIndex

### ISSUE THREAD

**Issue by inviso** [PeterStaev/NativeScript-Drop-Down#144] opened 2017-10-20 01:44 UTC
On IOS if I select a value from the dropdown, the selected item changes and everything seems fine.

If I change my mind and want to select another item, the scroll position on IOS is at the top again, even if I select e.g. the 10th element.

**Comment by PeterStaev** [comment] 2017-10-22 22:05
Hey @inviso , I cannot reproduce this behavior with the demo app. For example i Select `Item 22`, then when I open the drop down again the list is correctly scrolled down to Item 22. Can you provide more details or attach a small sample app that reproduces the problem?

**Comment by PeterStaev** [comment] 2017-11-04 08:24
No further response so closing this one for now. In case you still have problems, please provide more details.

**Closed by PeterStaev** 2017-11-04 08:24 UTC
Labels: bug, ios
