### ISSUE TITLE
Short Imports not used anymore NativeScript

### ISSUE THREAD

**Issue by talya07** [PeterStaev/NativeScript-Drop-Down#215] opened 2019-07-25 12:27 UTC
As Short Imports in NativeScript is not supported please fix imports in ( drop-down.d.ts ) file because it stops the application from running

**`ERROR in node_modules/nativescript-drop-down/drop-down.d.ts(16,33): error TS2307: Cannot find module 'data/observable-array'.`**
**`node_modules/nativescript-drop-down/drop-down.d.ts(17,62): error TS2307: Cannot find module 'ui/core/view'.`**
**`node_modules/nativescript-drop-down/drop-down.d.ts(18,30): error TS2307: Cannot find module 'ui/gestures/gestures'.`**
**`node_modules/nativescript-drop-down/drop-down.d.ts(19,29): error TS2307: Cannot find module 'ui/list-picker'.`**

**Comment by PeterStaev** [comment] 2019-07-25 12:47
Wrong. Short imports still work perfectly fine, they are only depreciated. You can read more in the duplicated issue below. 

Duplicate of #198

**Closed by PeterStaev** 2019-07-25 12:47 UTC
