### ISSUE TITLE
Error while selecting drop-down

### ISSUE THREAD

**Issue by LakshmiEvana** [PeterStaev/NativeScript-Drop-Down#143] opened 2017-10-18 10:56 UTC
Facing below issue while selecting drop-down.

![image](https://user-images.githubusercontent.com/17317992/31715384-41204d60-b421-11e7-8599-7263665f2496.png)

**Comment by PeterStaev** [comment] 2017-10-18 11:12
Duplicate of #136

**Closed by PeterStaev** 2017-10-18 11:12 UTC
